version: '3.8'
services:
  postgres:
    image: postgres:13-alpine3.22
    container_name: postgres-db
    environment:
      POSTGRES_USER: guilherme
      POSTGRES_PASSWORD: Senha080302
      POSTGRES_DB: TeachDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
