name: CI/CD .NET 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependências
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Testes de unidade
      run: dotnet test TeachingPlatform.UnitTest
      
    - name: Testes de Integração
      run: dotnet test TeachingPlatform.E2ETests
    
    - name: Geração de artefatos
      run: dotnet publish -c Release -o output

    - name: Upload artefato
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./output
